### ISSUE TITLE
2nd source of Bare MPR121 library

### ISSUE THREAD

**Issue by stefandz** [HerrPaule/BEAP-TOUCHBOARD-EXTENSION#1]
Hey HerrPaule

Stefan here from BareConductive. Great work on the Max/MSP plugin! One quick point - would you mind not including a modded version of our library / DataStream here? The main reason is that this risks people downloading from here, having issues because of the address change (c.f. our board) and then contacting us for support. Also, if we make improvements to the libraries, your users won't automatically benefit from them.

Instead, you could consider including instructions in your readme.md showing where users can manually alter the address of the MPR121 in datastream.ino?

Many thanks

Stefan

**Comment by HerrPaule** [comment]
Hey Stefan, 
no problem and sorry. I have deleted the modded library. I will create a short instruction as suggested by you. 

Best regards
Paul
